apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: secret-refresh-role
  namespace: tekton-pipelines
rules:
  - apiGroups: [""]
    resources: ["secrets"]
    verbs: ["get", "create", "update", "patch"]
