apiVersion: tekton.dev/v1
kind: Task
metadata:
  name: deploy-app
  namespace: tekton-pipelines
spec:
  params:
    - name: IMAGE_REPO
      type: string
    - name: IMAGE_TAG
      type: string

  steps:
    - name: deploy
      image: bitnami/kubectl:latest
      script: |
        #!/bin/sh
        set -e

        FULL_IMAGE="$(params.IMAGE_REPO):$(params.IMAGE_TAG)"

        echo "Deployando imagem: $FULL_IMAGE"

        kubectl set image deployment/phiz-tekton-app \
          app=$FULL_IMAGE \
          -n default

        kubectl rollout status deployment/phiz-tekton-app -n default

