apiVersion: tekton.dev/v1
kind: PipelineRun
metadata:
  generateName: phiz-app-ci-run-
  namespace: tekton-pipelines
spec:
  pipelineRef:
    name: ci-template

  taskRunTemplate:
    serviceAccountName: tekton-git-sa

  params:
    - name: REPO_URL
      value: git@github.com:rock02/phiz-tekton-poc-app.git

    - name: IMAGE_REPO
      value: 111546515233.dkr.ecr.us-east-1.amazonaws.com/phiz-tekton-app

  workspaces:
    - name: shared-data
      volumeClaimTemplate:
        spec:
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 2Gi

    - name: git-credentials
      secret:
        secretName: git-ssh-key
