apiVersion: batch/v1
kind: CronJob
metadata:
  name: ecr-secret-refresh
  namespace: tekton-pipelines
spec:
  schedule: "0 */6 * * *"
  jobTemplate:
    spec:
      template:
        spec:
          serviceAccountName: secret-refresh-sa
          restartPolicy: OnFailure
          containers:
            - name: refresh
              image: public.ecr.aws/aws-cli/aws-cli:2.15.0
              envFrom:
                - secretRef:
                    name: aws-credentials
              command:
                - /bin/sh
                - -c
                - |
                  set -e

                  echo "Instalando kubectl ARM64..."
                  curl -LO "https://dl.k8s.io/release/v1.29.0/bin/linux/arm64/kubectl"
                  chmod +x kubectl
                  mv kubectl /usr/local/bin/

                  echo "Gerando token ECR..."
                  TOKEN=$(aws ecr get-login-password --region $AWS_DEFAULT_REGION)

                  echo "Atualizando secret..."
                  kubectl create secret docker-registry ecr-secret \
                    --docker-server=111546515233.dkr.ecr.us-east-1.amazonaws.com \
                    --docker-username=AWS \
                    --docker-password="$TOKEN" \
                    --dry-run=client -o yaml \
                  | kubectl apply -f -

                  echo "Secret atualizado com sucesso."
